server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie

eureka:
  client:
    service-url:
      defaultZone: http://user:123456@peer1:8761/eureka/,http://user:123456@peer2:8762/eureka/
  instance:
    prefer-ip-address: true
feign.hystrix.enabled: false
