server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KennyJing/config-repo.git
          username: KennyJing
          password: jjd91011991
          clone-on-start: true
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG