server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@peer1:8761/eureka/
  instance:
    prefer-ip-address: true
#security:
#  basic:
#    enabled: true
#  user:
#    name: user
#    password: 123456